# Generated by Django 5.2.1 on 2025-05-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Имя автора"),
        ),
        migrations.AlterField(
            model_name="book",
            name="city",
            field=models.CharField(max_length=10, verbose_name="Откуда привезли книгу"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание книги"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(max_length=100, verbose_name="Жанр книги"),
        ),
        migrations.AlterField(
            model_name="book",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="books_photos/",
                verbose_name="Фото книги",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("Give", "Отдам"), ("Sell", "Продам"), ("Occupied", "Занято")],
                verbose_name="Статус книги",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название книги"),
        ),
    ]
